cons_format = "{icon}"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = " "

[icons]
icons = "awesome6"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid$frequency|Wired connection} "
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "88:C9:E8:40:49:7A"
disconnected_format = " $icon -"
format = " $icon $name{$percentage|}"
[[block.click]]
button = "left"
cmd = "blueberry"
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "battery"
#device = "BAT1"
interval = 5
format = " $icon $percentage $time"
missing_format = ""
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%b %-d %R') "
